### ISSUE TITLE
UTF-8 Character Issues with the Magpie

### ISSUE THREAD

**Issue by avoronkin** [splittingred/getFeed#2]
getFeed 1.0.0 beta2,Revolution 2.0.0-rc-3 rev7061.
It's return ???????????? for utf-8 encoded feeds (for example try http://modxcms-jp.com/rss.html or http://community.modx-cms.ru/rss/allcomments/ ).

Quick fix is to add this line to snippet code: 
`define('MAGPIE_OUTPUT_ENCODING', 'UTF-8');`
By default it is set  ISO-8859-1

**Comment by splittingred** [comment]
Fixed in 1.0.0-rc1
