### ISSUE TITLE
Stripping HTML attributes

### ISSUE THREAD

**Issue by goldsky** [splittingred/getFeed#4]
I was hoping that this feeder could strip HTML like simplepie does here http://simplepie.org/wiki/reference/simplepie/strip_attributes

I'm facing the multiple <br /> in one of my usage.

**Comment by goldsky** [comment]
geez.... i typed &lsaquo;br &frasl; &rsaquo;

**Comment by splittingred** [comment]
Use the :striptags output filter on your field.

**Comment by goldsky** [comment]
wow... beyond my expectation.
cool feature!
